### ISSUE TITLE
License file and package.json

### ISSUE THREAD

**Issue by KristjanESPERANTO** [PierreGode/MMM-PhoneDetect#1]
Thanks for this nice module. I like it!

Can you add a license file? And maybe also a `package.json`? This is not necessary for the functionality of the module, but for an optimal display in the [new module list](https://kristjanesperanto.github.io/MagicMirror-3rd-Party-Modules/) I am currently working on.

I would create the package.json like this:

```json
{
    "name": "mmm-phonedetect",
    "version": "1.0.0",
    "description": "A module for MagicMirror² to detect if phones are in network and turn on and off the mirror .",
    "repository": {
        "type": "git",
        "url": "git+https://github.com/PierreGode/MMM-PhoneDetect.git"
    },
    "keywords": [
        "magicmirror",
        "phone",
        "presence",
       "detection"
    ],
    "author": "PierreGode",
    "license": "MIT"
}
```

**Comment by PierreGode** [comment]
Hi!
thank you.


It is done!
Den 5 januari 2024 21:53:20 +01:00, skrev Kristjan ESPERANTO ***@***.***>:
