### ISSUE TITLE
Not detecting phone

### ISSUE THREAD

**Issue by ddriver88** [PierreGode/MMM-PhoneDetect#3]
Is there a method of debugging this that the user can perform? I've entered my mac address and reduced the timer for testing purpose, but it still never detects the phone in the first place. 

I'm curious if it may have to do with the pi hole I have on my network (though, I don't think it would)

**Comment by PierreGode** [comment]
This app uses nmap and arp-scan to "ping" your devices.

If you can test from the raspberry to nmap to your devices. You can also follow the logs in realtime with pm2 logs | grep Detect

**Comment by PierreGode** [comment]
No response for a week, I hope it works. Let me know if there are any issues.

**Comment by m4nino** [comment]
Hello, I've got the same issue, is it ok post here or should I open a new issue? 

edit: I can see a grey dot in my magic mirror, but the MM do nothing when my phone leave the house. 

When I check the log I get this:
m@raspberrypi:~ $ pm2 logs | grep Detect
0|MagicMir | [2024-06-06 16:13:57.502] [LOG]   MMM-PhoneDetect: Turning off the mirror... 
0|MagicMir | [2024-06-06 16:13:57.528] [LOG]   MMM-PhoneDetect: Mirror turned off. 
0|MagicMir | [2024-06-06 16:14:00.543] [LOG]   MMM-PhoneDetect: Turning off the mirror... 
0|MagicMir | [2024-06-06 16:14:00.576] [LOG]   MMM-PhoneDetect: Mirror turned off. 
0|MagicMir | [2024-06-06 16:14:07.462] [LOG]   MMM-PhoneDetect: Turning off the mirror... 
0|MagicMir | [2024-06-06 16:14:07.488] [LOG]   MMM-PhoneDetect: Mirror turned off. 
0|MagicMir | [2024-06-06 16:14:10.317] [LOG]   MMM-PhoneDetect: Turning off the mirror... 
0|MagicMir | [2024-06-06 16:14:10.344] [LOG]   MMM-PhoneDetect: Mirror turned off. 
0|MagicMir | [2024-06-06 16:14:14.843] [LOG]   MMM-PhoneDetect: Turning off the mirror... 
0|MagicMir | [2024-06-06 16:14:14.872] [LOG]   MMM-PhoneDetect: Mirror turned off. 
0|MagicMir | [2024-06-06 16:14:17.512] [LOG]   MMM-PhoneDetect: Turning off the mirror... 
0|MagicMir | [2024-06-06 16:14:17.538] [LOG]   MMM-PhoneDetect: Mirror turned off. 
0|MagicMir | [2024-06-06 16:14:31.879] [LOG]   MMM-PhoneDetect: Turning off the mirror... 
0|MagicMir | [2024-06-06 16:14:31.910] [LOG]   MMM-PhoneDetect: Mirror turned off. 
0|MagicMir | [2024-06-06 16:14:31.965] [LOG]   MMM-PhoneDetect: Turning off the mirror... 
0|MagicMirror  | [2024-06-06 16:14:32.002] [LOG]   MMM-PhoneDetect: Mirror turned off.

**Comment by PierreGode** [comment]
please verify that this commands work.
vcgencmd display_power 1 2 # Command to turn on the mirror
vcgencmd display_power 0 2 # Command to turn off the mirror

**Comment by m4nino** [comment]
When I write them in the terminal, nothing happen. Really nothing. And then I did change the dtoverlay=vc4-(f)kms-v3d, try again and there was no difference. Any ideas?

**Comment by m4nino** [comment]
When I write vcgencmd display_power 0 2 in the terminal, I get the answer display_power=1

And then I did change the dtoverlay=vc4-(f)kms-v3d, try again and there was no difference. Any ideas?
