### ISSUE TITLE
Question ????

### ISSUE THREAD

**Issue by Plainbroke** [PierreGode/MMM-PhoneDetect#4]
Can I use pm2 stop all and pm2 start mm instead of the vcgencmd display_power 0 2 and vcgencmd display_power 1 2 commands?
I ask because my tv I use turns off after 5 minutes of no input...

**Comment by PierreGode** [comment]
Hi! 
Sorry, stop and start mm is only for managing the magic mirror software, your OS will still be running.
I would recommend to test

https://www.thedigitalpictureframe.com/xrandr-the-new-command-to-turn-your-connected-monitor-on-and-off/

I will se if I can update this module to be working with bullseye when I find a stable solution.

/Pierre
